//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Panderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public articulo()
        {
            this.cabera_receta = new HashSet<cabera_receta>();
            this.detalle_receta = new HashSet<detalle_receta>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public int familiaId { get; set; }
        public int unidad_medidaId { get; set; }
        public string codigo_barra { get; set; }
        public string marca { get; set; }
        public string formato { get; set; }
    
        public virtual familia familia { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
        public virtual ICollection<cabera_receta> cabera_receta { get; set; }
        public virtual ICollection<detalle_receta> detalle_receta { get; set; }
    }
}
