//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Panderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_produccion
    {
        public int Id { get; set; }
        public decimal kilos { get; set; }
        public int cabera_recetaId { get; set; }
        public int cabecera_produccionId { get; set; }
    
        public virtual cabera_receta cabera_receta { get; set; }
        public virtual cabecera_produccion cabecera_produccion { get; set; }
    }
}
