//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Panderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class familia
    {
        public familia()
        {
            this.producto = new HashSet<articulo>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public int lineaId { get; set; }
    
        public virtual linea linea { get; set; }
        public virtual ICollection<articulo> producto { get; set; }
    }
}
