//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Panderia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pan_dbEntities : DbContext
    {
        public pan_dbEntities()
            : base("name=pan_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<unidad_medida> unidad_medidaSet { get; set; }
        public DbSet<linea> lineaSet { get; set; }
        public DbSet<familia> familiaSet { get; set; }
        public DbSet<articulo> articuloSet { get; set; }
        public DbSet<costo> costoSet { get; set; }
        public DbSet<precio_venta> precio_ventaSet { get; set; }
        public DbSet<cabera_receta> cabera_recetaSet { get; set; }
        public DbSet<detalle_receta> detalle_recetaSet { get; set; }
        public DbSet<cabecera_produccion> cabecera_produccionSet { get; set; }
        public DbSet<detalle_produccion> detalle_produccionSet { get; set; }
    }
}
